# Generated by Django 4.0.3 on 2022-07-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_rename_titulo_producto_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='stock',
            new_name='cantidad',
        ),
    ]
